--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Itzdvbravo/Tags
build-by-default: true
branches:
- master
projects:
  Tags:
    path: ""
    icon: "new.png"
    lint:
      phpstan: false
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.0.0  
...
