--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Itzdvbravo/Tags
build-by-default: true
branches:
- master
projects:
  Tags:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
    libs:
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^1.0.0  
...
