name: Tags
main: Itzdvbravo\Tags\TagManager

version: 0.2
api: 3.14.0

author: Itzdvbravo

depend: [PureChat, PurePerms]
commands:
 tag:
  description: Open tags UI
 givetag:
  description: Give someone a specific or random tag

permissions:
 tags.use:
  description: To use /tag command
 tags.give:
  description: To give others an item which you can interact to give tag.
